# Generated by Django 6.1 on 2026-09-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
